# Training mode: LoRA
# Base model:    Flux.1-dev
# Dataset:       Bruce the Gnome
# GPU:           1 x 40GB

type: FLUX_LORA
seed: 1
base_output_dir: output/experiments/bruce_the_gnome/flux_lora

optimizer:
  optimizer_type: AdamW
  learning_rate: 1e-4

lr_warmup_steps: 1
lr_scheduler: constant
transformer_learning_rate: 4e-4
text_encoder_learning_rate: 4e-4
train_text_encoder: False

data_loader:
  type: IMAGE_CAPTION_FLUX_DATA_LOADER
  dataset:
    type: IMAGE_CAPTION_JSONL_DATASET
    # Update the jsonl_path field to point to the metadata.jsonl file of the downloaded dataset.
    jsonl_path: sample_data/bruce_the_gnome/data.jsonl
  resolution: 768
  aspect_ratio_buckets:
    target_resolution: 768
    start_dim: 384
    end_dim: 1536
    divisible_by: 128
  caption_prefix: "bruce the gnome"
  dataloader_num_workers: 4

# General
model: black-forest-labs/FLUX.1-dev
gradient_accumulation_steps: 1
weight_dtype: bfloat16
gradient_checkpointing: True

max_train_steps: 350
save_every_n_steps: 50
validate_every_n_steps: 50

max_checkpoints: 10
validation_prompts:
  - A stuffed gnome at the beach with a pina colada in its hand.
  - A stuffed gnome reading a book in a cozy library.
  - A stuffed gnome sitting in a garden surrounded by colorful flowers and butterflies.
train_batch_size: 4
num_validation_images_per_prompt: 3