# Training mode: Textual Inversion with Masks
# Base model:    SDXL
# GPU:           1 x 24GB

type: SDXL_TEXTUAL_INVERSION
seed: 1
base_output_dir: output/bruce/sdxl_ti_masks

optimizer:
  optimizer_type: AdamW
  learning_rate: 5e-4

lr_scheduler: constant_with_warmup
lr_warmup_steps: 50

data_loader:
  type: TEXTUAL_INVERSION_SD_DATA_LOADER
  dataset:
    type: IMAGE_CAPTION_JSONL_DATASET
    jsonl_path: sample_data/bruce_the_gnome/data_masks.jsonl
    keep_in_memory: True
  caption_preset: object
  resolution: 1024
  center_crop: True
  random_flip: False
  shuffle_caption_delimiter: null

# General
model: stabilityai/stable-diffusion-xl-base-1.0
num_vectors: 16
placeholder_token: "bruce_the_gnome"
initializer_token: "gnome"
cache_vae_outputs: False
gradient_accumulation_steps: 1
weight_dtype: bfloat16
gradient_checkpointing: True

max_train_steps: 500
save_every_n_steps: 50
validate_every_n_steps: 50

use_masks: True

max_checkpoints: 10
validation_prompts:
  - A photo of bruce_the_gnome at the beach with a pina colada in its hand.
  - A photo of bruce_the_gnome reading a book in a cozy library.
train_batch_size: 4
num_validation_images_per_prompt: 3
